### ISSUE TITLE
DataFrame query fails for In filter

### ISSUE THREAD

**Issue by sadikovi** [sadikovi/riff#40]
```
scala> df.filter("id in (1, 2, 3)").count
17/05/10 18:15:21 INFO SparkSqlParser: Parsing command: id in (1, 2, 3)
17/05/10 18:15:21 INFO FileSourceStrategy: Pruning directories with: 
17/05/10 18:15:21 INFO FileSourceStrategy: Post-Scan Filters: id#0L IN (1,2,3)
17/05/10 18:15:21 INFO FileSourceStrategy: Output Data Schema: struct<id: bigint>
17/05/10 18:15:21 INFO FileSourceStrategy: Pushed Filters: In(id, [1,2,3])
17/05/10 18:15:21 INFO ContextCleaner: Cleaned accumulator 0
17/05/10 18:15:22 INFO CodeGenerator: Code generated in 355.646 ms
17/05/10 18:15:22 INFO CodeGenerator: Code generated in 26.276 ms
org.apache.spark.sql.catalyst.errors.package$TreeNodeException: execute, tree:
Exchange SinglePartition
+- *HashAggregate(keys=[], functions=[partial_count(1)], output=[count#15L])
   +- *Project
      +- *Filter id#0L IN (1,2,3)
         +- *FileScan riff [id#0L] Batched: false, Format: Riff, Location: InMemoryFileIndex[file:/Users/sadikovi/Developer/riff/temp/riff-test], PartitionFilters: [], PushedFilters: [In(id, [1,2,3])], ReadSchema: struct<id:bigint>

  at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:56)
  at org.apache.spark.sql.execution.exchange.ShuffleExchange.doExecute(ShuffleExchange.scala:112)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
  at org.apache.spark.sql.execution.InputAdapter.inputRDDs(WholeStageCodegenExec.scala:235)
  at org.apache.spark.sql.execution.aggregate.HashAggregateExec.inputRDDs(HashAggregateExec.scala:141)
  at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:368)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
  at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:225)
  at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:272)
  at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$execute$1$1.apply(Dataset.scala:2386)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
  at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2788)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$execute$1(Dataset.scala:2385)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collect(Dataset.scala:2392)
  at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2420)
  at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2419)
  at org.apache.spark.sql.Dataset.withCallback(Dataset.scala:2801)
  at org.apache.spark.sql.Dataset.count(Dataset.scala:2419)
  ... 50 elided
Caused by: java.lang.UnsupportedOperationException: Object [Ljava.lang.Object;@2e6c39ab of class [Ljava.lang.Object;
  at com.github.sadikovi.riff.tree.FilterApi.objToExpression(FilterApi.java:77)
  at com.github.sadikovi.riff.tree.FilterApi.in(FilterApi.java:146)
  at com.github.sadikovi.spark.riff.Filters$.recurBuild(Filters.scala:68)
  at com.github.sadikovi.spark.riff.Filters$.createRiffFilter(Filters.scala:41)
  at com.github.sadikovi.spark.riff.DefaultSource.buildReader(DefaultSource.scala:196)
  at org.apache.spark.sql.execution.datasources.FileFormat$class.buildReaderWithPartitionValues(FileFormat.scala:119)
  at com.github.sadikovi.spark.riff.DefaultSource.buildReaderWithPartitionValues(DefaultSource.scala:54)
  at org.apache.spark.sql.execution.FileSourceScanExec.inputRDD$lzycompute(DataSourceScanExec.scala:253)
  at org.apache.spark.sql.execution.FileSourceScanExec.inputRDD(DataSourceScanExec.scala:251)
  at org.apache.spark.sql.execution.FileSourceScanExec.inputRDDs(DataSourceScanExec.scala:271)
  at org.apache.spark.sql.execution.FilterExec.inputRDDs(basicPhysicalOperators.scala:124)
  at org.apache.spark.sql.execution.ProjectExec.inputRDDs(basicPhysicalOperators.scala:42)
  at org.apache.spark.sql.execution.aggregate.HashAggregateExec.inputRDDs(HashAggregateExec.scala:141)
  at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:368)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
  at org.apache.spark.sql.execution.exchange.ShuffleExchange.prepareShuffleDependency(ShuffleExchange.scala:85)
  at org.apache.spark.sql.execution.exchange.ShuffleExchange$$anonfun$doExecute$1.apply(ShuffleExchange.scala:121)
  at org.apache.spark.sql.execution.exchange.ShuffleExchange$$anonfun$doExecute$1.apply(ShuffleExchange.scala:112)
  at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:52)
  ... 77 more

scala> 
```

**Comment by sadikovi** [comment]
Fixed in #43.
