### ISSUE TITLE
Fails to read from HDFS with AssertionError

### ISSUE THREAD

**Issue by sadikovi** [sadikovi/riff#72]
```
Caused by: java.lang.AssertionError: Wrong magic number 48
  at com.github.sadikovi.riff.IndexedRowReader.readRowHeader(IndexedRowReader.java:74)
  at com.github.sadikovi.riff.IndexedRowReader.readRow(IndexedRowReader.java:120)
  at com.github.sadikovi.riff.Buffers$PredicateScanRowBuffer.hasNext(Buffers.java:372)
  at com.github.sadikovi.spark.riff.DefaultSource$$anonfun$buildReader$1$$anon$2.hasNext(DefaultSource.scala:239)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
  at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:102)
  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
  at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
  at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
```

**Comment by sadikovi** [comment]
This might be because of writing temporary files. PR #73 removes this dependency and should improve writes.

**Comment by sadikovi** [comment]
Looks like HDFS bug, current version 58e0394a665fe9b7176558d2717e8d403c5ac05a should work correctly.

**Comment by sadikovi** [comment]
I have file that reproduces this problem locally.
